### ISSUE TITLE
Player instructions/Marketing blurb

### ISSUE THREAD

**Issue by ConorMcPersonal** [ConorMcPersonal/Toaster#67]
We need some explanatory text to send with our submission

**Comment by mcmenaminadrian** [comment]
When humanity discovered fire what do you think was the first food they plunged into it? It was, of course, bread, the very staff of life, and so the best thing since before sliced bread - toast - was born.
Now in this new age of decadence things have moved on but not by far. We need something on which to lay our smashed avocado. And so toast is once again king of the foodstuffs.
That, anyway, is the vision of The Hotel Excess, your two (and a half) star slice of paradise (geddit?) right here on Neasden High Road. Owners Sid and Doris Bonkers have invested a lot of money in an all new, (only one previous owner), Murky Riddards ToastOMatic machine and  for some foolish reason you have applied for the job as operator and for an even more foolish reason they have given you it.
So how hard could it be?
You turn up at 7am and your shift ends at 11am. In between customers come to the bar and ask for toast. It will be quiet when you start but gets busy quickly before a calmer period and then a small rush mid-morning. You can see the orders and all you have to do is select one by typing the letter corresponding to the type. The ToastOMatic will select a free slot for your order.
Toasting is a scientific task and the ToastOmMatic lets you know how it's going, monitoring, in order, the temperature, the power in the slot and the moisture in the bread. Once the bread has dried it starts to toast and you need to pop it at the ideal moment (handily marked for you). Pop too soon and our customers will not be happy, too late and it starts to burn and you can set the smoke alarm off.
Popping is easy though - just pick the slot and press the number.
There are different types of bread all with different moisture contents and thicknesses - but you know that anyway, because why else would you have applied for the job? Right?
You are paid on a piece rate - that's measured by the score. Sid and Doris are modern employers so they won't ask you to pay them if you go into negative territory, but you will be asked to leave. Get to be too good and you will also be asked to leave, but we call that winning. If you manage that, do let us know!
Money isn't everything of course. There is also your reputation. And even more importantly there is Sid and Doris's reputation and so Sid keeps a beady eye on your behaviour. If you make him angry by serving too much bad toast you will be asked to leave.
Sid is also one of those people for whom enough is never good enough, so every day you work for him he is likely to have higher and higher expectations.
Good luck. We think you're going to need it.

**Comment by ConorMcPersonal** [comment]
Controls:
 - Letter keys add bread to the first available slot - use the capital letter in the order e.g. White = W, baGel = G, gluten Free = F.
 - Number keys 1-4 will pop toast out of that slot and serve to the first matching customer
